-- =====================================================================
-- SRI VENKATESHWARA MEDICAL STORE — PICKUP SCHEDULING COMPLETE FIX
-- Run this ENTIRE script in Supabase Dashboard → SQL Editor
-- =====================================================================

-- ── 1. DROP ALL CONFLICTING STORAGE POLICIES FOR prescriptions bucket ─

DROP POLICY IF EXISTS "admin_prescriptions_all"       ON storage.objects;
DROP POLICY IF EXISTS "customer_upload_policy"         ON storage.objects;
DROP POLICY IF EXISTS "anon_upload_prescriptions"      ON storage.objects;
DROP POLICY IF EXISTS "customer_read_policy"           ON storage.objects;
DROP POLICY IF EXISTS "anon_read_policy"               ON storage.objects;
DROP POLICY IF EXISTS "customer_update_policy"         ON storage.objects;
DROP POLICY IF EXISTS "customer_delete_policy"         ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_anon_upload"      ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_anon_read"        ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_anon_update"      ON storage.objects;
DROP POLICY IF EXISTS "Allow public uploads"           ON storage.objects;
DROP POLICY IF EXISTS "Allow public read access"       ON storage.objects;
DROP POLICY IF EXISTS "Allow anon uploads"             ON storage.objects;
DROP POLICY IF EXISTS "Allow anon read"                ON storage.objects;
-- New named policies from this script (idempotent)
DROP POLICY IF EXISTS "reservations_admin_all"         ON storage.objects;
DROP POLICY IF EXISTS "reservations_customer_insert"   ON storage.objects;
DROP POLICY IF EXISTS "reservations_customer_select"   ON storage.objects;
DROP POLICY IF EXISTS "reservations_customer_delete"   ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_anon_insert"      ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_auth_insert"      ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_auth_select"      ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_auth_delete"      ON storage.objects;
DROP POLICY IF EXISTS "quotes_auth_select"             ON storage.objects;

-- ── 2. STORAGE POLICIES FOR 'prescriptions' BUCKET ───────────────────
--
-- Folder structure:
--   prescriptions/      → raw prescription images (rx_<uid>_<ts>.jpg)
--   reservations/<uid>/ → per-user reservation PDFs
--   quotes/             → admin-generated quote PDFs
--

-- Policy A: Admin has full access to everything in 'prescriptions' bucket
CREATE POLICY "reservations_admin_all" ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'prescriptions'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    bucket_id = 'prescriptions'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Policy B: Authenticated customers can INSERT files into their own reservation folder
--   Path pattern: reservations/<their-uid>/anything
--   OR their own prescription image: rx_<uid>_anything
CREATE POLICY "reservations_customer_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'prescriptions'
    AND (
      -- Per-user reservation subfolder: reservations/{uid}/Reservation_XXX.pdf
      name LIKE 'reservations/' || auth.uid()::text || '/%'
      -- OR own prescription image at root
      OR name LIKE 'rx_' || auth.uid()::text || '_%'
    )
  );

-- Policy C: Authenticated customers can SELECT (read) their own files
--   - files they uploaded (owner = auth.uid())
--   - quote PDFs generated by admin (quotes/ folder)
CREATE POLICY "reservations_customer_select" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'prescriptions'
    AND (
      owner = auth.uid()
      OR name LIKE 'quotes/%'
      OR name LIKE 'reservations/' || auth.uid()::text || '/%'
    )
  );

-- Policy D: Authenticated customers can DELETE their own files
CREATE POLICY "reservations_customer_delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'prescriptions'
    AND owner = auth.uid()
  );

-- Policy E: Anonymous users can upload raw prescription images (rx_ prefix)
CREATE POLICY "prescriptions_anon_insert" ON storage.objects
  FOR INSERT TO anon
  WITH CHECK (
    bucket_id = 'prescriptions'
    AND name LIKE 'rx_%'
  );

-- Policy F: Anonymous users can read raw prescription images (for tracking)
CREATE POLICY "prescriptions_anon_select" ON storage.objects
  FOR SELECT TO anon
  USING (
    bucket_id = 'prescriptions'
    AND name LIKE 'rx_%'
  );


-- ── 3. ENSURE prescription_medicines RLS ALLOWS CUSTOMERS TO READ ────
--
-- Customers must be able to read medicines linked to their prescriptions

ALTER TABLE public.prescription_medicines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "customer_select_own_medicines"  ON public.prescription_medicines;
DROP POLICY IF EXISTS "admin_all_medicines"             ON public.prescription_medicines;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.prescription_medicines;

-- Admin: full access
CREATE POLICY "admin_all_medicines" ON public.prescription_medicines
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Customer: select medicines that belong to their prescriptions
CREATE POLICY "customer_select_own_medicines" ON public.prescription_medicines
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.prescriptions
      WHERE prescriptions.id = prescription_medicines.prescription_id
        AND prescriptions.user_id = auth.uid()
    )
  );


-- ── 4. ENSURE prescription_quotes RLS ALLOWS CUSTOMERS TO READ ───────

ALTER TABLE public.prescription_quotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "customer_select_own_quotes" ON public.prescription_quotes;
DROP POLICY IF EXISTS "admin_all_quotes"            ON public.prescription_quotes;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.prescription_quotes;

-- Admin: full access
CREATE POLICY "admin_all_quotes" ON public.prescription_quotes
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Customer: select quotes for their own prescriptions
CREATE POLICY "customer_select_own_quotes" ON public.prescription_quotes
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.prescriptions
      WHERE prescriptions.id = prescription_quotes.prescription_id
        AND prescriptions.user_id = auth.uid()
    )
  );


-- ── 5. ADD MISSING COLUMNS TO pickup_reservations (idempotent) ───────

ALTER TABLE public.pickup_reservations ADD COLUMN IF NOT EXISTS prescription_id  UUID REFERENCES public.prescriptions(id) ON DELETE SET NULL;
ALTER TABLE public.pickup_reservations ADD COLUMN IF NOT EXISTS collected_at     TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.pickup_reservations ADD COLUMN IF NOT EXISTS receipt_url      TEXT;
ALTER TABLE public.pickup_reservations ADD COLUMN IF NOT EXISTS qr_payload       TEXT;

-- ── 6. RELOAD SCHEMA CACHE ────────────────────────────────────────────
NOTIFY pgrst, 'reload schema';