-- =====================================================================
-- SRI VENKATESHWARA MEDICAL STORE — STORAGE RLS SECURITY AUDIT
-- Run this ENTIRE script in Supabase Dashboard → SQL Editor
-- =====================================================================

-- ── 1. DROP EXISTING STORAGE POLICIES ────────────────────────────────
DROP POLICY IF EXISTS "prescriptions_anon_upload" ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_anon_read" ON storage.objects;
DROP POLICY IF EXISTS "prescriptions_anon_update" ON storage.objects;
DROP POLICY IF EXISTS "Allow public uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow public read access" ON storage.objects;
DROP POLICY IF EXISTS "Allow anon uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow anon read" ON storage.objects;
DROP POLICY IF EXISTS "admin_prescriptions_all" ON storage.objects;
DROP POLICY IF EXISTS "customer_upload_policy" ON storage.objects;
DROP POLICY IF EXISTS "anon_upload_prescriptions" ON storage.objects;
DROP POLICY IF EXISTS "customer_read_policy" ON storage.objects;
DROP POLICY IF EXISTS "anon_read_policy" ON storage.objects;
DROP POLICY IF EXISTS "customer_update_policy" ON storage.objects;
DROP POLICY IF EXISTS "customer_delete_policy" ON storage.objects;

-- ── 2. CREATE PRODUCTION-READY STORAGE POLICIES ──────────────────────

-- Policy 1: Admin full read/write access to everything in 'prescriptions' bucket
CREATE POLICY "admin_prescriptions_all" ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'prescriptions'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    bucket_id = 'prescriptions'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Policy 2: Customer upload restrictions (INSERT)
-- Authenticated customers can only upload reservation PDFs into 'reservations/'
-- or their own prescription files into root (prefixed with 'rx_<user_id>_')
CREATE POLICY "customer_upload_policy" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'prescriptions'
    AND (
      name LIKE 'reservations/%'
      OR name LIKE 'rx_' || auth.uid()::text || '_%'
    )
  );

-- Policy 3: Anon upload restrictions (INSERT)
-- Guest users can upload prescriptions to the root bucket (prefixed with 'rx_')
CREATE POLICY "anon_upload_prescriptions" ON storage.objects
  FOR INSERT TO anon
  WITH CHECK (
    bucket_id = 'prescriptions'
    AND name LIKE 'rx_%'
  );

-- Policy 4: Customer read access (SELECT)
-- Authenticated customers can read their own uploaded files (reservations/prescriptions)
-- and quotes generated by administrators.
CREATE POLICY "customer_read_policy" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'prescriptions'
    AND (
      auth.uid() = owner
      OR name LIKE 'quotes/%'
    )
  );

-- Policy 5: Anon read access (SELECT)
-- Guest users can only read prescription files (for tracking purposes),
-- but have absolutely no access to reservations or quotes.
CREATE POLICY "anon_read_policy" ON storage.objects
  FOR SELECT TO anon
  USING (
    bucket_id = 'prescriptions'
    AND name LIKE 'rx_%'
  );

-- Policy 6: Customer update access (UPDATE)
-- Customers can only modify files they own
CREATE POLICY "customer_update_policy" ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'prescriptions'
    AND auth.uid() = owner
  )
  WITH CHECK (
    bucket_id = 'prescriptions'
    AND auth.uid() = owner
  );

-- Policy 7: Customer delete access (DELETE)
-- Customers can only delete files they own
CREATE POLICY "customer_delete_policy" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'prescriptions'
    AND auth.uid() = owner
  );
