import React, { useState } from 'react';
import { useAdmin } from '../context/AdminContext';
import AdminLayout from '../components/AdminLayout';
import { revenueData } from '../data/mockData';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { Download, FileText, FileSpreadsheet } from 'lucide-react';
import { SkeletonStatGrid, SkeletonBlock, ErrorState } from '../../components/LoadingStates';

const Reports = () => {
  const { metrics, products, orders, customers, dataLoading, dataError, refetchAllData } = useAdmin();
  const [reportTab, setReportTab] = useState('sales');
  const [dateFrom, setDateFrom] = useState('2026-06-01');
  const [dateTo, setDateTo] = useState(new Date().toISOString().split('T')[0]);

  if (dataLoading) {
    return (
      <AdminLayout>
        <div className="page-header">
          <div className="page-header-left"><h1>Reports &amp; Analytics</h1><p>Loading data…</p></div>
        </div>
        <SkeletonStatGrid cards={4} />
        <div style={{ marginTop: 20, borderRadius: 12, overflow: 'hidden', border: '1px solid var(--border)' }}>
          <SkeletonBlock height={260} style={{ borderRadius: 12 }} />
        </div>
      </AdminLayout>
    );
  }

  if (dataError) {
    return (
      <AdminLayout>
        <div className="page-header">
          <div className="page-header-left"><h1>Reports &amp; Analytics</h1></div>
        </div>
        <ErrorState message={dataError} onRetry={refetchAllData} />
      </AdminLayout>
    );
  }

  const totalRevenue = orders.filter(o => o.status === 'Completed').reduce((s, o) => s + o.total, 0);
  const avgOrderValue = orders.filter(o => o.status === 'Completed').length > 0
    ? Math.round(totalRevenue / orders.filter(o => o.status === 'Completed').length)
    : 0;

  const customersWithStats = customers.map(c => {
    const customerOrders = orders.filter(o => o.user_id === c.id);
    const totalSpent = customerOrders.reduce((sum, o) => sum + o.total, 0);
    const lastOrder = customerOrders[0];
    const lastActivity = lastOrder ? lastOrder.date : 'Never';
    return {
      ...c,
      ordersCount: customerOrders.length,
      totalSpent,
      lastActivity
    };
  });

  const exportCSV = (filename, rows) => {
    const csv = rows.map(r => Object.values(r).join(',')).join('\n');
    const headers = Object.keys(rows[0]).join(',');
    const blob = new Blob([headers + '\n' + csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
  };

  const exportPDF = (title) => {
    const w = window.open('', '_blank');
    w.document.write(`<html><head><title>${title}</title><style>body{font-family:sans-serif;padding:24px}h1{color:#0891b2;border-bottom:2px solid #0891b2;padding-bottom:8px}table{width:100%;border-collapse:collapse;margin-top:16px}th{background:#e0f2fe;padding:8px;text-align:left}td{border-bottom:1px solid #ddd;padding:8px}.footer{margin-top:24px;font-size:12px;color:#666}</style></head><body><h1>${title}</h1><p>Generated: ${new Date().toLocaleString('en-IN')} | Period: ${dateFrom} to ${dateTo}</p><table><tr>${reportTab === 'sales' ? '<th>Metric</th><th>Value</th>' : '<th>Product</th><th>Stock</th><th>Revenue</th>'}</tr>${reportTab === 'sales' ? `<tr><td>Total Revenue</td><td>₹${totalRevenue.toLocaleString()}</td></tr><tr><td>Total Orders</td><td>${metrics.totalOrders}</td></tr><tr><td>Avg Order Value</td><td>₹${avgOrderValue}</td></tr><tr><td>Completed Orders</td><td>${metrics.completedOrders}</td></tr>` : products.slice(0, 10).map(p => `<tr><td>${p.name}</td><td>${p.stock}</td><td>₹${(p.price * (300 - p.stock)).toLocaleString()}</td></tr>`).join('')}</table><div class="footer">Sri Venkateshwara Medical & General Stores · Report generated by Admin Panel</div></body></html>`);
    w.document.close(); w.print();
  };

  return (
    <AdminLayout>
      <div className="page-header">
        <div className="page-header-left">
          <h1>Reports & Analytics</h1>
          <p>Comprehensive business insights and export options</p>
        </div>
        <div className="page-header-actions">
          <button className="btn btn-secondary" onClick={() => exportCSV('svms_report.csv', orders.slice(0, 20).map(o => ({ id: o.id, customer: o.customerName, date: o.date, total: o.total, status: o.status })))}>
            <FileSpreadsheet size={14} /> Export CSV
          </button>
          <button className="btn btn-primary" onClick={() => exportPDF('SVMS Sales Report')}>
            <FileText size={14} /> Export PDF
          </button>
        </div>
      </div>

      {/* Date Range */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 20, alignItems: 'center', flexWrap: 'wrap' }}>
        <div className="form-group" style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
          <label className="form-label" style={{ whiteSpace: 'nowrap' }}>From</label>
          <input className="form-input" type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} style={{ width: 160 }} />
        </div>
        <div className="form-group" style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
          <label className="form-label" style={{ whiteSpace: 'nowrap' }}>To</label>
          <input className="form-input" type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} style={{ width: 160 }} />
        </div>
        {['This Week', 'This Month', 'Last 3 Months'].map(r => (
          <button key={r} className="btn btn-secondary btn-sm">{r}</button>
        ))}
      </div>

      {/* Report Tabs */}
      <div className="tab-bar" style={{ marginBottom: 20 }}>
        {[
          { key: 'sales', label: '💰 Sales Report' },
          { key: 'products', label: '💊 Product Report' },
          { key: 'customers', label: '👥 Customer Report' },
          { key: 'inventory', label: '📦 Inventory Report' },
        ].map(t => (
          <button key={t.key} className={`tab-btn${reportTab === t.key ? ' active' : ''}`} onClick={() => setReportTab(t.key)}>
            {t.label}
          </button>
        ))}
      </div>

      {reportTab === 'sales' && (
        <>
          <div className="report-grid" style={{ marginBottom: 24 }}>
            {[
              { label: 'Total Revenue', value: `₹${totalRevenue.toLocaleString()}`, color: 'var(--cyan)' },
              { label: 'Total Orders', value: metrics.totalOrders, color: 'var(--indigo)' },
              { label: 'Avg. Order Value', value: `₹${avgOrderValue}`, color: 'var(--green)' },
              { label: 'Completed Orders', value: metrics.completedOrders, color: 'var(--purple)' },
              { label: 'Cancelled Orders', value: metrics.cancelledOrders, color: 'var(--red)' },
              { label: 'Cancellation Rate', value: `${metrics.totalOrders ? Math.round((metrics.cancelledOrders / metrics.totalOrders) * 100) : 0}%`, color: 'var(--amber)' },
            ].map(c => (
              <div key={c.label} className="report-card" style={{ borderTop: `3px solid ${c.color}` }}>
                <div className="report-card-value" style={{ color: c.color }}>{c.value}</div>
                <div className="report-card-label">{c.label}</div>
              </div>
            ))}
          </div>
          <div className="chart-card">
            <div className="chart-header"><div className="chart-title">Revenue Trend (Last 7 Days)</div></div>
            <ResponsiveContainer width="100%" height={240}>
              <LineChart data={revenueData['7d']}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                <XAxis dataKey="day" tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={v => `₹${v >= 1000 ? (v/1000).toFixed(0)+'K' : v}`} />
                <Tooltip contentStyle={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 8, color: 'var(--text-primary)', fontSize: 12 }} />
                <Line type="monotone" dataKey="revenue" stroke="var(--cyan)" strokeWidth={2.5} dot={false} />
                <Line type="monotone" dataKey="orders" stroke="var(--indigo)" strokeWidth={2} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </>
      )}

      {reportTab === 'products' && (
        <>
          <div className="report-grid" style={{ marginBottom: 24 }}>
            {[
              { label: 'Total Products', value: metrics.totalProducts, color: 'var(--cyan)' },
              { label: 'In Stock', value: products.filter(p => p.stock > 10).length, color: 'var(--green)' },
              { label: 'Low Stock', value: metrics.lowStock, color: 'var(--amber)' },
              { label: 'Out of Stock', value: metrics.outOfStock, color: 'var(--red)' },
            ].map(c => (
              <div key={c.label} className="report-card" style={{ borderTop: `3px solid ${c.color}` }}>
                <div className="report-card-value" style={{ color: c.color }}>{c.value}</div>
                <div className="report-card-label">{c.label}</div>
              </div>
            ))}
          </div>
          <div className="table-card">
            <div className="table-toolbar"><span className="table-title">Product Performance</span></div>
            <table className="admin-table">
              <thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Est. Revenue</th><th>Status</th></tr></thead>
              <tbody>
                {products.map(p => (
                  <tr key={p.id}>
                    <td style={{ fontWeight: 600 }}>{p.name}</td>
                    <td className="muted">{p.category}</td>
                    <td>₹{p.price}</td>
                    <td>{p.stock}</td>
                    <td style={{ fontWeight: 600 }}>₹{(p.price * Math.max(300 - p.stock, 0)).toLocaleString()}</td>
                    <td><span className={`badge ${p.stock === 0 ? 'badge-out-stock' : p.stock <= 10 ? 'badge-low-stock' : 'badge-in-stock'}`}>{p.stock === 0 ? 'Out' : p.stock <= 10 ? 'Low' : 'OK'}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {reportTab === 'customers' && (
        <>
          <div className="report-grid" style={{ marginBottom: 24 }}>
            {[
              { label: 'Total Customers', value: metrics.totalCustomers, color: 'var(--cyan)' },
              { label: 'New This Month', value: metrics.newCustomers, color: 'var(--green)' },
              { label: 'Avg. Spend/Customer', value: `₹${customers.length ? Math.round(totalRevenue / customers.length) : 0}`, color: 'var(--indigo)' },
              { label: 'Repeat Customers', value: customersWithStats.filter(c => c.ordersCount > 1).length, color: 'var(--purple)' },
            ].map(c => (
              <div key={c.label} className="report-card" style={{ borderTop: `3px solid ${c.color}` }}>
                <div className="report-card-value" style={{ color: c.color }}>{c.value}</div>
                <div className="report-card-label">{c.label}</div>
              </div>
            ))}
          </div>
          <div className="table-card">
            <div className="table-toolbar"><span className="table-title">Top Customers by Spending</span></div>
            <table className="admin-table">
              <thead><tr><th>Customer</th><th>Phone</th><th>Orders</th><th>Total Spent</th><th>Last Active</th></tr></thead>
              <tbody>
                {[...customersWithStats].sort((a, b) => b.totalSpent - a.totalSpent).slice(0, 10).map(c => (
                  <tr key={c.id}>
                    <td style={{ fontWeight: 600 }}>{c.name}</td>
                    <td className="muted">{c.phone}</td>
                    <td>{c.ordersCount}</td>
                    <td style={{ fontWeight: 700, color: 'var(--cyan)' }}>₹{(c.totalSpent || 0).toLocaleString()}</td>
                    <td className="muted">{c.lastActivity}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {reportTab === 'inventory' && (
        <>
          <div className="report-grid" style={{ marginBottom: 24 }}>
            {[
              { label: 'Total SKUs', value: products.length, color: 'var(--cyan)' },
              { label: 'Total Stock Units', value: products.reduce((s, p) => s + p.stock, 0), color: 'var(--green)' },
              { label: 'Inventory Value (Cost)', value: `₹${products.reduce((s, p) => s + p.price * p.stock, 0).toLocaleString()}`, color: 'var(--indigo)' },
              { label: 'Inventory Value (MRP)', value: `₹${products.reduce((s, p) => s + p.mrp * p.stock, 0).toLocaleString()}`, color: 'var(--purple)' },
            ].map(c => (
              <div key={c.label} className="report-card" style={{ borderTop: `3px solid ${c.color}` }}>
                <div className="report-card-value" style={{ color: c.color, fontSize: 18 }}>{c.value}</div>
                <div className="report-card-label">{c.label}</div>
              </div>
            ))}
          </div>
          <div className="chart-card">
            <div className="chart-header"><div className="chart-title">Stock by Category</div></div>
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={[...new Set(products.map(p => p.category))].map(cat => ({ category: cat, stock: products.filter(p => p.category === cat).reduce((s, p) => s + p.stock, 0) }))}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                <XAxis dataKey="category" tick={{ fill: 'var(--text-muted)', fontSize: 10 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 8, color: 'var(--text-primary)', fontSize: 12 }} />
                <Bar dataKey="stock" fill="var(--cyan)" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </>
      )}
    </AdminLayout>
  );
};

export default Reports;
